services:
  passman-api:
    build: ./PassManAPI
    ports:
      - "5246:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=passManDB;User=root;Password=hihi;Pooling=true
    depends_on:
      db:
        condition: service_healthy
  db:
   image: mysql:8.0
   container_name: db
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=hihi
     - MYSQL_DATABASE=passManDB
   volumes:
     - mysql-data:/var/lib/mysql
   healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-phihi"]
     interval: 5s
     timeout: 5s
     retries: 10

volumes:
  mysql-data:
    driver: local