services:
  passman-api:
    build: ./PassManAPI
    ports:
      - "5246:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  db:
   image: mysql:8.0
   container_name: db
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=hihi
     - MYSQL_DATABASE=passManDB
   volumes:
     - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local